apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-worker-deployment
  labels:
    app: async-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-worker
  template:
    metadata:
      labels:
        app: async-worker
    spec:
      containers:
  
      - name: async-worker
        image: dracarys2000/celery-asm-worker:v1.0
        ports:
        - containerPort: 5055
        imagePullPolicy: Always
        env:
        - name: NGROK_PORT
          value: "<port>"  
        - name: CELERY_BROKER_URL
          value: "redis://redis-message-broker-service:6379"  
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-message-broker-service:6379"  
        - name: EMAIL_ADDRESS
          value: "<email-address>"  
        - name: EMAIL_PASSWORD
          value: "<email-password>"        
        
---
apiVersion: v1
kind: Service
metadata:
  name: async-worker-service
spec:
  type: NodePort
  selector:
    app: async-worker
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 6379
      nodePort: 30001