apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-message-broker-deployment
  labels:
    app: redis-message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-message-broker
  template:
    metadata:
      labels:
        app: redis-message-broker
    spec:
      containers:
      - name: redis-message-broker-container
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        imagePullPolicy: Always 

---
apiVersion: v1
kind: Service
metadata:
  name: redis-message-broker-service
spec:
  type: NodePort
  selector:
    app: redis-message-broker
  ports:
    - protocol: TCP
      port: 6379   #whenever wants to call the service this will be the port 
      targetPort: 6379
      nodePort: 30003