apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager-deployment
  labels:
    app: service-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-manager
  template:
    metadata:
      labels:
        app: service-manager
    spec:
      containers:

      - name: service-manager
        image: dracarys2000/service-manager:v1.1
        ports:
        - containerPort: 5050
        imagePullPolicy: Always
        env:
        env:
        - name: NGROK_PORT
          value: "17712"  
        - name: CELERY_BROKER_URL
          value: "redis://redis-message-broker-service:6379"  
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-message-broker-service:6379"  
        - name: EMAIL_ADDRESS
          value: "<email-address>"  
        - name: EMAIL_PASSWORD
          value: "<email-password>"  
        
---
apiVersion: v1
kind: Service
metadata:
  name: service-manager-service
spec:
  type: NodePort
  selector:
    app: service-manager
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 31111