name: Publish celery worker Docker image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push worker Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: dracarys2000/celery-asm-worker
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker/.
          file: docker/async_consumer.Dockerfile
          push: true
          tags: dracarys2000/celery-asm-worker:v1.0
          labels: ${{ steps.meta.outputs.labels }}
